version: "{build}"

platform:
  - x64

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

os: Windows Server 2012

skip_tags: true

skip_commits:
  message: /\[ci skip\]/

install:
  - cmd: java -version
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

build: off

test_script:
  - ./mvnw test -B

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
